pulse:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'SYSADMIN') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'PULSE_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'PULSE') }}"
      schema: MARTS
      threads: 4